apiVersion: v1
kind: Service
metadata:
  name: ms-perfilamiento
  namespace: solventa-staging
spec:
  selector:
    app: ms-perfilamiento
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
